# Generated by Django 3.1.5 on 2022-07-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate_data',
            name='ancillary_building_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='area_square_meter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='balcony_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='berth_shifting_total_area_square_meter',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='building_present_situation_pattern_compartmented',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='building_present_situation_pattern_hall',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='building_present_situation_pattern_health',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='building_present_situation_pattern_room',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='has_manages_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='main_building_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='number_plate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='shifting_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='the_berth_total_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='the_district',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='total_floor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='total_price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='transaction_pen_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='transaction_sign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='realestate_data',
            name='use_zoning',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
