# Generated by Django 3.1.5 on 2022-07-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220710_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate_data',
            name='the_unit_price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
