# Generated by Django 3.1.5 on 2022-07-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220710_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='realestate_data_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_district', models.CharField(blank=True, max_length=200)),
                ('total_floor', models.CharField(blank=True, max_length=200)),
                ('building_state', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
